apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
  labels:
    app: smalllinks
data:
  BASE_URL: "a806fed51340e4e628e7aa95580dcedd-1942025403.us-east-1.elb.amazonaws.com"
  PORT: "8201"
  SHORTENER_DEBUG: "true"
  SHORT_URL_LENGTH: "5"
  SHORT_KEY_GENERATION_RETRIES_COUNT: "5"
  KAFKA_HOST: "broker:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  LOG_LEVEL: "info"