apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smalllinks-monitor
  namespace: observability
  labels:
    # KEEP THESE (so you don't break existing management)
    app.kubernetes.io/instance: observability-stack
    app.kubernetes.io/managed-by: Helm
    # ADD THIS (The key Prometheus Operator is looking for)
    release: observability-stack
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: smalllinks
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s