apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
stringData:
  # PostgreSQL expects these exact variable names
  POSTGRES_USER: "kuttuser"
  POSTGRES_PASSWORD: "MySecurePassword123"
  POSTGRES_DB: "kutt_db"
  # These are for the app to connect
  DB_USER: "kuttuser"
  DB_PASSWORD: "MySecurePassword123"
  DB_NAME: "kutt_db"
  
  #the application requires a JWT_SECRET to run in production mode
  JWT_SECRET: "a-very-long-random-string-12345"
